DROP TABLE IF EXISTS OrderModifier CASCADE;
DROP TABLE IF EXISTS OrderDetail CASCADE;
DROP TABLE IF EXISTS ProductModifier CASCADE;
DROP TABLE IF EXISTS ProductIngredient CASCADE;

DROP TABLE IF EXISTS "order" CASCADE;
DROP TABLE IF EXISTS ModifierOption CASCADE;

DROP TABLE IF EXISTS Product CASCADE;
DROP TABLE IF EXISTS Inventory CASCADE;
DROP TABLE IF EXISTS Employee CASCADE;
